export const ENV_VARS = {
  STRIPE: {
    PUBLISHABLE_KEY: 'VITE_STRIPE_PUBLISHABLE_KEY',
    SECRET_KEY: 'VITE_STRIPE_SECRET_KEY',
    CLIENT_ID: 'VITE_STRIPE_CLIENT_ID',
  },
  SUPABASE: {
    URL: 'VITE_SUPABASE_URL',
    ANON_KEY: 'VITE_SUPABASE_ANON_KEY',
  },
  APP: {
    URL: 'VITE_APP_URL',
  },
} as const;

export const REQUIRED_ENV_VARS = [
  ENV_VARS.STRIPE.PUBLISHABLE_KEY,
  ENV_VARS.STRIPE.SECRET_KEY,
  ENV_VARS.STRIPE.CLIENT_ID,
  ENV_VARS.SUPABASE.URL,
  ENV_VARS.SUPABASE.ANON_KEY,
  ENV_VARS.APP.URL,
] as const;