export const ENV_KEYS = {
  STRIPE: {
    PUBLISHABLE_KEY: 'VITE_STRIPE_PUBLISHABLE_KEY',
    SECRET_KEY: 'VITE_STRIPE_SECRET_KEY',
    CLIENT_ID: 'VITE_STRIPE_CLIENT_ID',
  },
  SUPABASE: {
    URL: 'VITE_SUPABASE_URL',
    ANON_KEY: 'VITE_SUPABASE_ANON_KEY',
  },
  APP: {
    URL: 'VITE_APP_URL',
  },
  GOOGLE: {
    MAPS_API_KEY: 'VITE_GOOGLE_MAPS_API_KEY',
  },
  MIXPANEL: {
    TOKEN: 'VITE_MIXPANEL_TOKEN',
  },
} as const;