-- First, clear any existing rules
delete from public.state_rules;

-- Insert default state rules with basic restrictions
insert into public.state_rules (
    state_code,
    state_name,
    allows_import,
    allows_export,
    max_transport_miles,
    requires_certification_beyond_miles,
    certification_miles_threshold,
    certification_details,
    additional_requirements
) values
    ('AL', 'Alabama', true, true, 100, true, 50, 'State certification required for transport beyond 50 miles', null),
    ('AK', 'Alaska', true, true, 100, false, null, null, 'Special permits may be required for remote areas'),
    ('AZ', 'Arizona', true, true, 150, true, 75, 'Heat treatment certification required for distances over 75 miles', 'Drought restrictions may apply'),
    ('AR', 'Arkansas', true, true, 100, true, 50, 'USDA compliance certificate required beyond 50 miles', null),
    ('CA', 'California', true, false, 50, true, 25, 'CDFA certification required for transport beyond 25 miles', 'Strict quarantine zones in effect'),
    ('CO', 'Colorado', true, true, 200, true, 100, 'State phytosanitary certificate required beyond 100 miles', null),
    ('CT', 'Connecticut', true, true, 75, true, 50, 'State compliance agreement required beyond 50 miles', null),
    ('DE', 'Delaware', true, true, 50, false, null, null, null),
    ('FL', 'Florida', true, false, 75, true, 50, 'FDACS certification required beyond 50 miles', 'Special regulations for pine firewood'),
    ('GA', 'Georgia', true, true, 100, true, 75, 'State agricultural certificate required beyond 75 miles', null),
    ('HI', 'Hawaii', false, false, 50, true, 25, 'HDOA certification required for all transport', 'Strict quarantine regulations'),
    ('ID', 'Idaho', true, true, 150, true, 100, 'State compliance certificate required beyond 100 miles', null),
    ('IL', 'Illinois', true, true, 100, true, 50, 'IDA certification required beyond 50 miles', null),
    ('IN', 'Indiana', true, true, 100, true, 75, 'State compliance agreement required beyond 75 miles', null),
    ('IA', 'Iowa', true, true, 150, true, 100, 'State phytosanitary certificate required beyond 100 miles', null),
    ('KS', 'Kansas', true, true, 200, true, 150, 'KDA certification required beyond 150 miles', null),
    ('KY', 'Kentucky', true, true, 100, true, 75, 'State compliance agreement required beyond 75 miles', null),
    ('LA', 'Louisiana', true, true, 100, true, 50, 'LDAF certification required beyond 50 miles', null),
    ('ME', 'Maine', true, true, 75, true, 50, 'State compliance certificate required beyond 50 miles', 'Special regulations for out-of-state transport'),
    ('MD', 'Maryland', true, true, 75, true, 50, 'MDA certification required beyond 50 miles', null),
    ('MA', 'Massachusetts', true, true, 75, true, 50, 'State compliance agreement required beyond 50 miles', null),
    ('MI', 'Michigan', true, true, 100, true, 75, 'MDARD certification required beyond 75 miles', null),
    ('MN', 'Minnesota', true, true, 100, true, 75, 'State compliance certificate required beyond 75 miles', null),
    ('MS', 'Mississippi', true, true, 100, true, 50, 'State agricultural permit required beyond 50 miles', null),
    ('MO', 'Missouri', true, true, 150, true, 100, 'State compliance agreement required beyond 100 miles', null),
    ('MT', 'Montana', true, true, 200, true, 150, 'State certification required beyond 150 miles', null),
    ('NE', 'Nebraska', true, true, 150, true, 100, 'State compliance certificate required beyond 100 miles', null),
    ('NV', 'Nevada', true, true, 150, true, 100, 'State agricultural certificate required beyond 100 miles', null),
    ('NH', 'New Hampshire', true, true, 75, true, 50, 'State compliance agreement required beyond 50 miles', null),
    ('NJ', 'New Jersey', true, true, 50, true, 25, 'NJDA certification required beyond 25 miles', null),
    ('NM', 'New Mexico', true, true, 150, true, 100, 'State compliance certificate required beyond 100 miles', null),
    ('NY', 'New York', true, true, 100, true, 50, 'State certification required beyond 50 miles', null),
    ('NC', 'North Carolina', true, true, 100, true, 75, 'NCDA certification required beyond 75 miles', null),
    ('ND', 'North Dakota', true, true, 200, true, 150, 'State compliance agreement required beyond 150 miles', null),
    ('OH', 'Ohio', true, true, 100, true, 75, 'State agricultural certificate required beyond 75 miles', null),
    ('OK', 'Oklahoma', true, true, 150, true, 100, 'State compliance certificate required beyond 100 miles', null),
    ('OR', 'Oregon', true, false, 75, true, 50, 'ODA certification required beyond 50 miles', 'Special regulations for certain wood species'),
    ('PA', 'Pennsylvania', true, true, 100, true, 75, 'State compliance agreement required beyond 75 miles', null),
    ('RI', 'Rhode Island', true, true, 50, true, 25, 'State certification required beyond 25 miles', null),
    ('SC', 'South Carolina', true, true, 100, true, 75, 'State compliance certificate required beyond 75 miles', null),
    ('SD', 'South Dakota', true, true, 200, true, 150, 'State agricultural permit required beyond 150 miles', null),
    ('TN', 'Tennessee', true, true, 100, true, 75, 'State compliance agreement required beyond 75 miles', null),
    ('TX', 'Texas', true, true, 200, true, 150, 'TDA certification required beyond 150 miles', null),
    ('UT', 'Utah', true, true, 150, true, 100, 'State compliance certificate required beyond 100 miles', null),
    ('VT', 'Vermont', true, true, 75, true, 50, 'State agricultural permit required beyond 50 miles', null),
    ('VA', 'Virginia', true, true, 100, true, 75, 'VDACS certification required beyond 75 miles', null),
    ('WA', 'Washington', true, false, 75, true, 50, 'WSDA certification required beyond 50 miles', 'Special regulations for certain wood species'),
    ('WV', 'West Virginia', true, true, 100, true, 75, 'State compliance agreement required beyond 75 miles', null),
    ('WI', 'Wisconsin', true, true, 100, true, 75, 'DATCP certification required beyond 75 miles', null),
    ('WY', 'Wyoming', true, true, 200, true, 150, 'State agricultural certificate required beyond 150 miles', null);

-- Force schema cache refresh
notify pgrst, 'reload schema';